### PR TITLE
Add pgn 129283 cross track error

### PR DESCRIPTION
**Pull request by sbender9**
I'm not sure if this is the best or correct way to store state, but I figured it would be good have a common place to store any state that needs shared between pgns.

### CODE REVIEW

**Comment by sbender9** [comment]
How's this? 

Pull request to to node server coming if this is ok.

**Comment by tkurki** [comment]
State.js is no longer used, so remove that?
Naming is now a bit confusing with two contexts. Should the calling context be called state?

**Comment by sbender9** [comment]
Ha. I had it names state aa first, then looked at your comment and you used the word context ;) I'll switch it back and remove state.js...

**Comment by tkurki** [comment]
Now there is just one global state. If there are two different sources with different settings should we account for that, key the state properties per src?

**Comment by sbender9** [comment]
Not sure why this test is failing. It does not fail in my branch

**Comment by sbender9** [comment]
Starting over one more time...

**Pull request closed without merging**
