### PR TITLE
Added waypointArrival notification

### PR DESCRIPTION
**Pull request by sbender9**
Added waypointArrival notification

### CODE REVIEW

**Comment by sbender9** [comment]
I guess I should not be including pgn , etc. Is there a way to keep those out?

**Comment by sbender9** [comment]
OK, I think I figured this stuff out. Give me some time to fix all of these...

**Comment by sbender9** [comment]
Is this the right way to do these notifications? I found today while I was actually out on the boat testing with real data, the notification would get set and then never go away. This code now always creates the notification, but with state: normal unless your actually in the "Arrival Circle".

**Comment by sbender9** [comment]
I also can't get this to pass the test. It doesn't like the 'method'.

if I make method:

```
method: 'visual'
```

Then it complains:
```
    AssertionError: [object Object]/vessels/urn:mrn:imo:mmsi:230099999/notifications/waypointArrival/method:Invalid type: string
```

If I make it an array:
```
method: [ 'visual' ],
```
Then it complains:
```
     AssertionError: expected { Object (mmsi, navigation, ...) } to have a deep property 'notifications.waypointArrival.method' of 'visual', but got [ 'visual' ]
```

**Comment by rob42** [comment]
You can clear the notification by deleting it (eg set it to null), or set to normal as you discovered.
I will look into the ['visual'] stuff.

**Pull request closed without merging**
