### PR TITLE
Add missing data and pgns for AIS

### PR DESCRIPTION
**Pull request by sbender9**
Adding multiple  missing pgns and fields from existing pgns relates to AIS

### CODE REVIEW

**Comment by sbender9** [comment]
I think the failing test should be fixed once @rob42 's schema changes are merged.

**Comment by rob42** [comment]
Yes probably. My branch runs ok, and up to date with this oddly.

The errors are around `$source`, etc, Ive made some updates to those as many have explicit `source` and `timestamp` rather than $ref to definitions `commonValues`. 

Still odd that travis doesnt test ok.

**Comment by tkurki** [comment]
I fixed an issue with sources in the schema, but @sbender9  you can trick Travis into using the ais version of the schema by changing signalk-schema to point to version `signalk/specification#aisAdditions` (uses version from Github instead of npm and uses the branch).

FYI I fixed a bunch of errors in n2k-signalk caused by more strict timestamp validation in schema validation.

**Comment by sbender9** [comment]
Not sure why "129284 Navigation Data complete sentence converts" is failing now

**Comment by tkurki** [comment]
129284 fixed in fd468d6e2aa0322eb3ab97f9e9b786843077e22a

Master of n2k-signalk was using a fixed version of signalk-schema and was not up to date.

**Comment by tkurki** [comment]
The new test files are missing schema validation tests.

**Comment by sbender9** [comment]
@tkurki how do I implement aisShipType so it does not have .value?

**Comment by tkurki** [comment]
Not possible at the moment.

**Comment by sbender9** [comment]
@rob42 and @tkurki can you look at these errors? (ignore the aisShipType error for now)

Should aircraft, aton and sar be required?

**Comment by rob42** [comment]
One of vessels, aircraft, aton, sar is required. When you get this kind of error

/vessels/urn:mrn:imo:mmsi:230099999:Missing required property: url
/vessels/urn:mrn:imo:mmsi:230099999:Missing required property: uuid
:Missing required property: aircraft
:Missing required property: aton
:Missing required property: sar

it generally means that the vessels object failed validation, so it considered 'not to be there', and the script tests for at least one of the others. When they are not found either you see these messages.

Add a uuid or mmsi to the vessels.

**Comment by sbender9** [comment]
OK, so the error is probably because of the shipType error.

**Comment by sbender9** [comment]
@tkurki can we merge this now that the spec changes have been merged?

**Comment by tkurki** [comment]
Sure. I'll publish a new version of signalk-schema and you should then update package.json to reflect that.

**Comment by tkurki** [comment]
Merged in b1a64c11f99ae7e9ac0ca2508da8d9d6361f22fc.

**Pull request closed without merging**
