### PR TITLE
Added 129283 Cross Track Error

### PR DESCRIPTION
**Pull request by sbender9**
Is this path right? I don't have the "calculation type", So can't put it under there unless we want to hard code it.

### CODE REVIEW

**Comment by tkurki** [comment]
Hmm. The path is not correct, but this is a bit troublesome as you've noticed. 

Let me get back to you on this.

**Comment by sbender9** [comment]
Anything on this?

**Comment by tkurki** [comment]
Sorry, had forgotten about this. Will resume.

**Comment by sbender9** [comment]
I hate to say it, but is the right thing to not have the calculation type part of the path, but as a property instead? Or could both types exist at the same time?

**Comment by sbender9** [comment]
I don't think the spec changes addresses this issue. The course calculation type does not come along with the N2K XTE pgn. I could store the state of the last calc type from 129284 (navigation data).

**Comment by tkurki** [comment]
Let's make this stateful per your suggestion.

**Comment by sbender9** [comment]
New pull request #68

**Pull request closed without merging**
