### PR TITLE
add: magneticDeviation and speedThroughWaterReferenceType

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by rob42** [comment]
Does magnetic variation differ from declination? We already have declination, and we long ago we decided that Signalk would store absolute values - that is values after all known adjustments were applied. Hence a compass value would be adjusted for compass error either by the compass itself, the gateway, or by the first server (assuming it held a correction).

Like using std units, its greatly simplifies the problem of propagating data across networks when you can assume its the best known (corrected) value.

**Comment by tkurki** [comment]
@rob42 what you said about always storing the corrected value is not 100% true or realistic: 
- then we would not have courseOverGroundMagnetic
- what if the only instrument you have is a magnetic compass?

**Comment by tkurki** [comment]
`navigation.magneticVariation`: http://signalk.org/specification/0.0.1-12/doc/vesselsBranch.html#vesselsregexpnavigationmagneticvariation

No reference type for STW in the schema though.

**Comment by rob42** [comment]
@tkurki true, but what was decided (as far as I remember) was that values would be corrected at source, rather than send values and corrections across the network. So in the case above courseOverGroundMagnetic would be adjusted for compass deviation if we knew it (and had the capability), and if we didnt know local declination we could not estimate true heading

I not sure what magneticVariation represents in n2k, and concerned that we are starting to store corrections, when we should simply correct the data. 

It still works both ways as converting n2k 90deg + 1deg variation to signalk 91deg, just means that when its converted back to n2k its 91deg + 0deg variation.

**Comment by tkurki** [comment]
If somebody wants or needs access to magneticVariation from their n2k network for some reason I think n2k-signalk should support that conversion. 

Do you think we should explicitly not support that and not add this conversion?

This PR does not do anything about conversions between true and magnetic values.

**Comment by rob42** [comment]
Is magneticVariation in this context different to declination (http://signalk.org/specification/0.0.1-12/doc/vesselsBranch.html#vesselsregexpnavigationmagneticvariation) which we already have?. 

If not then it should just go in http://signalk.org/specification/0.0.1-12/doc/vesselsBranch.html#vesselsregexpnavigationmagneticvariation

If it is different then what is the difference?

**Comment by sbender9** [comment]
It’s different : https://en.wikipedia.org/wiki/Magnetic_deviation

**Comment by rob42** [comment]
Ok. If its local compass inaccuracy then we should correct it (at gateway) before sending the data further, since its much too complex to always check every signalk value for possible corrections and adjust at the receiver. 

But if there is a use case for converting back into the original inaccurate n2k we should store the value.

**Comment by tkurki** [comment]
Oh my goodness, this is a very confused issue.

The code change is about deviation (and water speed reference).
The issue name says variation.
Rob mentioned

**Comment by rob42** [comment]
See the wiki article.
"The first is magnetic declination or variation—the angular difference between magnetic North (the local direction of the Earth's magnetic field) and true North.[1] The second is magnetic deviation—the angular difference between magnetic North and the compass needle due to nearby sources of interference such as magnetically permeable bodies, or other magnetic fields within the field of influence.[2]"

To rephrase:
If its local compass inaccuracy (magnetic deviation) then we should correct it (at gateway) before sending the data further, since its much too complex to always check every signalk value for possible corrections and adjust at the receiver.

But if there is a valid use case for converting back into the original inaccurate n2k we should store the value. But call it what it something that will not be confused with our existing `navigation.magneticVariation`

BTW - speedThroughWaterReferenceType is good, include it.

**Comment by tkurki** [comment]
Fixed variation => deviation in commit message, squashed and force pushed.

Fixed PR title.

**Pull request merged**
