### PR TITLE
feature: add pgn 129793 AIS base station

### PR DESCRIPTION
**Pull request by tkurki**

### CODE REVIEW

**Comment by bastiaanbrouwer** [comment]
Proposal is to name it as follow:
shore.ais
With this in mind also the following can be implemented:

shore.bridge : for bridge opening times an d position
shore.marina: for marina information Like free places, depth of the marina. 
shore.fuelstation
shore.lock: for opening times and position

**Comment by tkurki** [comment]
Sorry about letting this lapse. My problem is that I don't want to be hasty with schema additions, and i don't want to add a top level `basestations` or `shore` driven by an ais special case. I am not too crazy about aton top level branch - in hindsight`ais.atons` and `ais.basestations` would have made more sense imho.

But I don't want to get stopped by analysis paralysis. I'm going to merge this as `shore.basestations` without adding it to the schema. We can revisit the issue later with more proerly thought out solution if needed.

**Comment by tkurki** [comment]
Published in @signalk/n2k-signalk@1.5.0

**Comment by bastiaanbrouwer** [comment]
Thanks very much for adding this. I fully understand it takes time. Thanks so far. Saturday I will be home from business trip to work with this extra data.

**Pull request merged**
