### PR TITLE
feature: add ais class

### PR DESCRIPTION
**Pull request by tkurki**
Includes commits in  #162

### CODE REVIEW

**Comment by sbender9** [comment]
Tests are failing

**Comment by tkurki** [comment]
That was intentional, as AIS class is not in spec yet, but having failing tests in master is more trouble than it is worth.

Tests commented out with TODOs, amended and force pushed. Merge this, then rebase others on master?

**Comment by tkurki** [comment]
Better luck if you actually include the changes...

**Comment by sbender9** [comment]
https://github.com/SignalK/specification/issues/563

**Pull request merged**
