### PR TITLE
feature: object valued properties under value in full model

### PR DESCRIPTION
**Pull request by tkurki**
Adjust code to match changes in https://github.com/SignalK/specification/pull/315.

### CODE REVIEW

**Comment by sbender9** [comment]
Now we also don't get meta for things like design.beam. Not sure if that is handled by another change? Or is even possible now?

**Comment by tkurki** [comment]
Can you describe the overwrite problem in more detail? Did you test that with server's signalk-schema from the object values branch, more specifically `fullsignalk.js`?

**Comment by sbender9** [comment]
I did not test with the correct schema branch. Looks better now.

These changes do break lots with WilhelmSK. I'm going to have to make some big architectural changes to support both the old way and the new, but I think this makes sense going forward.

**Comment by sbender9** [comment]
Actually, going to break everyone I suspect. Definitely my anchor alarm.

What about also putting the attributes a level up also for backwards compatibility?

**Comment by tkurki** [comment]
>putting the attributes a level up also

how?

**Comment by sbender9** [comment]
The full tree could look like this:
```         
"position" : {
             "latitude" : 38.9506583,
             "longitude" : -76.4068499
            "value" : {
               "latitude" : 38.9506583,
               "longitude" : -76.4068499
            },
            "pgn" : 129038,
            "timestamp" : "2017-04-15T16:45:45.647Z",
            "meta" : {
               "description" : "The position of the vessel in 2 or 3 dimensions (WGS84 datum)"
            },
            "$source" : "n2kFromFile.43"
         },
```

**Comment by tkurki** [comment]
Sorry, no dice. Either we change things or we don't.

**Comment by sbender9** [comment]
Let's change it, I'll handle things on the client side.

**Pull request merged**
