### PR TITLE
Battery status

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by sbender9** [comment]
Still not sure this is right. It complains about source, pgn, timestamp, etc. 

```
{
        "batteries": {
          "0": {
            "$source": "n2kFromFile.17", 
            "pgn": 127508, 
            "timestamp": "2016-08-22T16:02:56.773Z", 
            "voltage": 13.03
          }, 
          "1": {
            "$source": "n2kFromFile.17", 
            "pgn": 127508, 
            "timestamp": "2016-08-22T16:02:58.275Z", 
            "voltage": 13.11
          }
        }
      }
```

**Comment by tkurki** [comment]
You should return the full path in the `node`. 

For the actual value field you can use just `source: 'Voltage'`.

Then in test specify `...value`, as in some of the other mappings.

The output is supposed to be like https://github.com/SignalK/specification/blob/master/test/data/electrical.json#L22-L25

**Comment by tkurki** [comment]
Source, pgn and timestamp will be children of the path you specify in `node`, maybe that mental model helps?

**Comment by tkurki** [comment]
Thanks!

**Pull request merged**
