### PR TITLE
add: pgn 129285 Route/WP Information

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by tkurki** [comment]
Something special about the lodash version?

**Comment by sbender9** [comment]
Not sure what happened there. I swear I tried to use lodash and it was not found, so I npm installed it.

**Comment by sbender9** [comment]
Do you think this makes from the spec point of view? I could not find anything existing for the current route.

**Comment by tkurki** [comment]
Looks good to time

**Pull request merged**
