### PR TITLE
Splitup mappings into separate groups for better organization

### PR DESCRIPTION
**Pull request by sbender9**
I'm guessing there's a better way to do this?

+extend(mappings, require('./groups/environment').mappings)
+extend(mappings, require('./groups/navigation').mappings)
+extend(mappings, require('./groups/steering').mappings)
+extend(mappings, require('./groups/propulsion').mappings)
+extend(mappings, require('./groups/tanks').mappings)
+extend(mappings, require('./groups/electrical').mappings)
+extend(mappings, require('./groups/raymarine').mappings)

### CODE REVIEW

**Comment by tkurki** [comment]
How about https://lodash.com/docs/4.17.2#assign ?

But are you quite sure the SK hierarchies are the correct split? With n2k-signalk it is usually about a PGN, or a group of PGNs. That is how the tests are organised and that way when you are working on adding a PGN the git diffs are really clear - like what files were touched immediately tell you what happened.

So if you split them up by PGN number to filename, like 128267, and export like so

128267.js
```
//Water depth
module.exports = [{
    source: 'Depth',
    node: 'environment.depth.belowTransducer'
  }, {
    source: 'Offset',
    node: 'environment.depth.surfaceToTransducer'
  }, {
    node: 'environment.depth.belowSurface',
    filter: function(n2k) {
      return typeof n2k.fields['Depth'] != 'undefined' && typeof n2k.fields['Offset'] != 'undefined'
    },
    value: function(n2k) {
      return Number(n2k.fields.Depth) + Number(n2k.fields.Offset)
    }
  }]
```

you can require them programmatically and assign the required object (array actually) to property derived from the filename.

Also IDEs / editors are really good at opening files when you type the name of the file, which is the pgn.

Sorry, I should have brought this up earlier, but i must have thought it obvious - obvious because that's the way I thought myself...

**Comment by sbender9** [comment]
Yeah, I kinda went back and forth between the options. Didn't think about the benefits on the git and ide side. 

How do I required them programmatically?

**Comment by sbender9** [comment]
I think I have something figured out for requiring programmatically.

I did kinda like having the proprietary pgns separated. What do think about having them under a different directory for each vendor?

**Comment by sbender9** [comment]
I'm going to start a new pull request since this is pretty convoluted now

**Pull request closed without merging**
